server:
  port: 9000

jwt:
  secret_key:[the value of your key]
  expiration_time: 86400000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/School_Managment_DB
    username: postgres
    password:[your password] 

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
